### ISSUE TITLE
Problem with the source of /tmp/local-usage.txt in disk monitor

### ISSUE THREAD

**Issue by rangwani-harsh** [ThomasRobertFr/gpu-monitor#1]
Hi @ThomasRobertFr ,
Thanks for the awesome tool. Can you please let me know the source of the /tmp/local-usage.txt file that you use in gpu-run.sh. That's intended to have disk usage as per my understanding. Can you please let me know how to generate that file?

Thanks

**Comment by ThomasRobertFr** [comment]
Hi, this is a feature we have to monitor the individual usage of a shared local SSD mounted at `/local`. The file `local-usage.txt` is produced by a cron ran by root of the command `du -h -d 1 /local > /tmp/local-usage.txt`. This tells you which folders are the biggest, since there is 1 folder per user. This way you know who to ask if it's full.
